name: Default Assignee (Set default assignee and link issue)

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened]

jobs:
  assign_assignee:
    # This job will run only if (issue or pull_request is opened or edited) and assignees is empty
    if: (github.event_name == 'issues' || github.event_name == 'pull_request') && github.event.action == 'opened' && github.event.assignee == null
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            ${{ github.actor }}
          numberOfAssignees: 1
          addReviewers: false
  link_issue:
    # This job will run only if (pull request is opened or edited) and issue is not linked
    if: github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '#### Issue')
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-prefix: '/#'
          header: '#### Issue'
          position: 'top'

