name: Post Merged with Label
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'auto')
    runs-on: ubuntu-latest
    steps:
    - run: echo "merged!"
