name: Post Merged with Label
on:
  pull_request:
    types:
      - closed
env:
  APP_SLUG: ${{ secrets.BITRISE_SLUG }}
  BITRISE_TOKEN: ${{ secrets.BITRISE_TOKEN }}

jobs:
  post_merged:
    runs-on: ubuntu-latest
    steps:
    - name: Set outputs
      id: bitrise
      run: echo "SLUG=${APP_SLUG};TOKEN=${BITRISE_TOKEN};" >> $GITHUB_OUTPUT
    - name: Curl
      run: |
          curl -X POST \
          -H "accept: application/json" \
          -H "Authorization: ${{ steps.vars.outputs.TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{ \"build_params\": { \"workflow_id\": \"test-curl\", \"branch\": \"main\" }, \"hook_info\": { \"type\": \"bitrise\" }}" \
          "https://api.bitrise.io/v0.1/apps/${{ steps.bitrise.outputs.SLUG }}/builds"

